"""initial migrations

Revision ID: f35c9698ed52
Revises: 680e00f54d00
Create Date: 2024-05-14 18:55:44.409013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35c9698ed52'
down_revision = '680e00f54d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
